### ISSUE TITLE
ShellCheck is missing at least on some slaves

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#22]
EL6 slave SSG build:

```
Skipping ShellCheck analysis, ensure shellcheck executable is present in the PATH!
```

**Comment by jan-cerny** [comment]
@mpreisler ShellCheck is not available in RHEL6 repositories. It is possible to install it from the sources, see https://github.com/koalaman/shellcheck/wiki/More-Installation-Guides . However I don't feel comfortable to deploy some custom software on our infrastructure, because we will have to maintain that manually. Therefore I suggest closing this issue. What is your opinion on this?

**Comment by mpreisler** [comment]
I see... In that case let's close this.
